import type { Article, CalendarBlock, GuideField, MeetingPlan, Prefs, Task } from './types'

export const defaultPrefs: Prefs = {
  theme: 'system',
  motion: 'system',
  solidSurfaces: false,
  density: 'comfortable',
  textScale: 1,
  font: 'system',
  todayView: 'kanban',
  bufferMinutes: 10,
  quietStart: '18:30',
  quietEnd: '08:30',
  summaryFirst: true,
  soundEnabled: true,
  soundVolume: 0.7,
}

export const seedBlocks: CalendarBlock[] = [
  { id: 'b1', title: 'Team check-in', start: '09:30', end: '09:50', kind: 'meeting', meetingId: 'm1' },
  { id: 'b2', title: 'Transition time', start: '09:50', end: '10:00', kind: 'buffer' },
  { id: 'b3', title: 'Focus block', start: '10:00', end: '11:30', kind: 'focus' },
  { id: 'b4', title: 'Q3 planning review', start: '11:30', end: '12:30', kind: 'meeting', meetingId: 'm2' },
  { id: 'b5', title: 'Lunch break', start: '12:30', end: '13:30', kind: 'break' },
  { id: 'b6', title: 'Preparation: design critique', start: '14:30', end: '14:50', kind: 'buffer' },
  { id: 'b7', title: 'Design critique', start: '15:00', end: '15:45', kind: 'meeting', meetingId: 'm3' },
]

export const seedTasks: Task[] = [
  {
    id: 't1',
    title: 'Draft the onboarding checklist outline',
    why: 'Maya needs a first version to review before Thursday.',
    minutes: 45,
    state: 'ready',
    start: '10:00',
    source: 'Clarify: message from Maya, Monday',
    doneWhen: 'A one-page outline with section headings is shared with Maya.',
  },
  {
    id: 't2',
    title: 'Reply to Sam about the report format',
    why: 'Sam asked which format the monthly report should use.',
    minutes: 15,
    state: 'planned',
    start: '10:45',
    source: 'Quick capture',
  },
  {
    id: 't3',
    title: 'Check Q3 budget figures against last quarter',
    why: 'Prepares your contribution for the planning review.',
    minutes: 30,
    state: 'planned',
    start: '13:45',
    source: 'Meeting: Q3 planning review',
  },
  { id: 't4', title: 'Book a room for the accessibility workshop', minutes: 10, state: 'planned', source: 'Quick capture' },
  { id: 't5', title: 'Read the updated flexible working policy', minutes: 20, state: 'planned', source: 'Knowledge' },
]

export const seedGuide: GuideField[] = [
  { id: 'g1', label: 'Preferred communication format', hint: 'For example: written first, then a call if needed.', value: 'Written first · Send the topic in advance', audience: 'team' },
  { id: 'g2', label: 'Amount of context I find useful', hint: 'Short summary or full background first?', value: 'Summary first · Full background', audience: 'team' },
  { id: 'g3', label: 'Helpful feedback style', hint: 'How do you prefer to receive feedback?', value: 'In writing · Specific examples · Time to respond', audience: 'selected' },
  { id: 'g4', label: 'Meeting participation', hint: 'What helps you contribute well in meetings?', value: 'Agenda beforehand · Time to think before answering', audience: 'organization' },
  { id: 'g5', label: 'Focus hours and interruptions', hint: 'When are you most able to focus?', value: 'Mornings · Messages are fine · No unplanned calls', audience: 'team' },
  { id: 'g6', label: 'How urgency should be communicated', hint: 'What does “urgent” mean to you?', value: 'Give a specific time', audience: 'organization' },
  { id: 'g7', label: 'Ways to confirm understanding', hint: 'How can we check we are aligned?', value: 'I summarise back · Written recap', audience: 'team' },
  { id: 'g8', label: 'Optional identity or accommodation information', hint: 'Entirely optional. Never required to use any feature.', value: '', audience: 'private' },
]

export const seedMeetings: MeetingPlan[] = [
  {
    id: 'm1',
    title: 'Team check-in',
    organizer: 'Maya Chen',
    start: '09:30',
    end: '09:50',
    purpose: 'Share priorities for the day and flag anything that is blocked.',
    outcome: 'Everyone knows who is working on what today.',
    role: 'Participant',
    contribution: 'One sentence on your main task and any blocker.',
    decisionOwner: 'Maya Chen',
    materials: 'None',
    prep: 'Check Today view for your main task.',
    agenda: [
      { id: 'a1', title: 'Round of priorities', minutes: 12 },
      { id: 'a2', title: 'Blockers and help needed', minutes: 8 },
    ],
    decisions: [], actions: [], questions: [], privateNotes: '', parkingLot: [],
  },
  {
    id: 'm2',
    title: 'Q3 planning review',
    organizer: 'Jordan Lee',
    start: '11:30',
    end: '12:30',
    purpose: 'Review Q3 plan against budget.',
    outcome: '',
    role: '',
    contribution: '',
    decisionOwner: '',
    materials: 'Q3 plan draft (shared drive)',
    prep: 'Read the Q3 plan draft.',
    agenda: [
      { id: 'a1', title: 'Budget overview', minutes: 15 },
      { id: 'a2', title: 'Team priorities for Q3', minutes: 25 },
      { id: 'a3', title: 'Risks and dependencies', minutes: 15 },
      { id: 'a4', title: 'Agree next steps', minutes: 5 },
    ],
    decisions: [], actions: [], questions: [], privateNotes: '', parkingLot: [],
  },
  {
    id: 'm3',
    title: 'Design critique',
    organizer: 'Priya Nair',
    start: '15:00',
    end: '15:45',
    purpose: '',
    outcome: '',
    role: 'Presenter',
    contribution: 'Walk through the onboarding flow mock-ups.',
    decisionOwner: 'Priya Nair',
    materials: 'Figma file: Onboarding v2',
    prep: '',
    agenda: [],
    decisions: [], actions: [], questions: [], privateNotes: '', parkingLot: [],
  },
]

export const articles: Article[] = [
  {
    id: 'k1',
    title: 'Writing explicit requests',
    summary: 'State the action, the output, the owner, and the time. Avoid “when you get a chance”.',
    body: 'A clear request answers four questions: What should be done? What should the result look like? Who is doing it? When is it needed? Replace relative time words such as “soon” or “ASAP” with a specific time. If a request is optional, say so.',
    owner: 'People & Culture',
    source: 'Inclusive Communication Handbook §2',
    version: 'v3.1',
    lastReviewed: '2026-06-02',
    nextReview: '2026-12-02',
    tags: ['communication', 'templates'],
  },
  {
    id: 'k2',
    title: 'Running predictable meetings',
    summary: 'Share purpose, outcome, agenda, and expected contributions at least one working day ahead.',
    body: 'Every invitation should say why the meeting exists and what decision or output is expected. List each person’s expected contribution. Allow processing time: it is fine to pause for questions and to follow up in writing.',
    owner: 'Operations',
    source: 'Meeting Standards',
    version: 'v2.0',
    lastReviewed: '2026-03-14',
    nextReview: '2026-09-14',
    tags: ['meetings', 'managers'],
  },
  {
    id: 'k3',
    title: 'Giving useful feedback',
    summary: 'Specific, written, and paired with an example. Offer time to respond.',
    body: 'Describe the observed work, not the person. Give one concrete example and one concrete suggestion. Ask the colleague how they prefer to receive feedback — their Working Guide may already say.',
    owner: 'People & Culture',
    source: 'Manager Guide §5',
    version: 'v1.4',
    lastReviewed: '2026-08-20',
    nextReview: '2027-02-20',
    tags: ['feedback', 'managers'],
  },
  {
    id: 'k4',
    title: 'Requesting a workplace adjustment',
    summary: 'The formal route for adjustments. You do not need a diagnosis to ask.',
    body: 'Adjustments can be requested through your manager or directly with HR. You can describe what helps without naming a condition. This app does not make or record accommodation decisions.',
    owner: 'HR Services',
    source: 'Workplace Adjustments Policy',
    version: 'v4.0',
    lastReviewed: '2026-05-01',
    nextReview: '2026-11-01',
    tags: ['policy', 'support'],
  },
]

export const weekPlan: { day: string; items: { title: string; kind: string }[] }[] = [
  { day: 'Mon', items: [{ title: 'Sprint planning', kind: 'meeting' }, { title: 'Focus: research notes', kind: 'focus' }] },
  { day: 'Tue', items: [{ title: 'Focus: onboarding outline', kind: 'focus' }, { title: '1:1 with Maya', kind: 'meeting' }] },
  { day: 'Wed', items: [] },
  { day: 'Thu', items: [{ title: 'Checklist review with Maya', kind: 'meeting' }, { title: 'Focus: budget figures', kind: 'focus' }] },
  { day: 'Fri', items: [{ title: 'Accessibility workshop', kind: 'meeting' }, { title: 'Weekly reset', kind: 'break' }] },
]
